# Generated by Django 3.2 on 2021-04-14 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ConstructionReporter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_name', models.CharField(max_length=200)),
                ('defect_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DefectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_status', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Respondent',
        ),
        migrations.RemoveField(
            model_name='locationtype',
            name='teee',
        ),
        migrations.AlterField(
            model_name='location',
            name='location_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ConstructionReporter.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ConstructionReporter.locationtype'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_user_group',
            field=models.ManyToManyField(to='auth.Group'),
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
        migrations.AddField(
            model_name='defect',
            name='defect_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConstructionReporter.location'),
        ),
        migrations.AddField(
            model_name='defect',
            name='defect_respondent',
            field=models.ManyToManyField(blank=True, null=True, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='defect',
            name='defect_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConstructionReporter.defectstatus'),
        ),
        migrations.AddField(
            model_name='defect',
            name='media_files',
            field=models.ManyToManyField(blank=True, null=True, to='ConstructionReporter.MediaFile'),
        ),
    ]
