# Generated by Django 3.2 on 2021-04-11 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConstructionReporter', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Defect',
        ),
        migrations.DeleteModel(
            name='DefectStatus',
        ),
    ]
