# Generated by Django 3.2 on 2021-04-12 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConstructionReporter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationtype',
            name='teee',
        ),
    ]
