# Generated by Django 3.2 on 2021-05-12 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ConstructionReporter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defect',
            name='defect_respondent',
        ),
        migrations.AddField(
            model_name='defect',
            name='defect_respondent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
            preserve_default=False,
        ),
    ]
