# Generated by Django 3.2 on 2021-04-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConstructionReporter', '0002_auto_20210414_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
