# Generated by Django 3.2 on 2021-04-13 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConstructionReporter', '0002_remove_locationtype_teee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ConstructionReporter.locationtype'),
        ),
    ]
